import java.util.*;

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        int sum = 0;
        for(char c : t.toCharArray()) {
            sum += c;
        }
        for(char c : s.toCharArray()) {
            sum -= c;
        }
        return (char)sum;
    }
    
    public char findTheDifferenceExtraSpace(String s, String t) {
        List<Character> chars = new ArrayList<>();
        for(char c : s.toCharArray()) {
            chars.add(c);
        }
        for(char c : t.toCharArray()) {
            if(!chars.contains(c)) {
                return c;
            } else {
                chars.remove((Character)c);
            }
        }
        return ' ';
    }
}